  version: '3'
  services:
    ms-sql-server:
      image: mcr.microsoft.com/mssql/server
      environment: 
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Str0ngPa55w0rd"
        MSSQL_PID: Express
      ports:
        - "1433:1433"
    securityapi:
      build: .
      ports:
        - "80:80"
        - "443:5001"
    